
export GRAPHTOOL_ROOT=~/projects/GraphTool
export GRAPHTOOL_USER_ROOT=$GRAPHTOOL_ROOT/examples
export CONFIG_ROOT=$GRAPHTOOL_USER_ROOT/config

export PYTHONPATH=$GRAPHTOOL_USER_ROOT/src:$GRAPHTOOL_ROOT/src:$PYTHONPATH
export PATH=$GRAPHTOOL_USER_ROOT/tools:$PATH

